#!/usr/bin/env python3
"""The bridge must not leave a client on a stale tool list (T2, schema half).

Run from the repo root:  python3 -m unittest discover -s scripts/tests -p 'test_bridge*.py' -v

scripts/tools_schema.py is a checked-in file regenerated by hand, and the bridge answers the very
first tools/list from it when OrcaSlicer is not up yet -- the normal case, because the MCP client
starts first. Without a tools/list_changed notification the client keeps whatever that file said
for the life of the session, which is how get_presets' filters were unreachable from a session
whose running server had them.
"""

import importlib.util
import os
import sys
import unittest
from unittest import mock

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
BRIDGE_PATH = os.path.join(REPO_ROOT, "scripts", "orcamcp-bridge.py")


def load_bridge():
    sys.path.insert(0, os.path.join(REPO_ROOT, "scripts"))
    spec = importlib.util.spec_from_file_location("orcamcp_bridge", BRIDGE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ListChangedCapabilityTests(unittest.TestCase):
    def test_initialize_advertises_listChanged(self):
        bridge = load_bridge()
        response = bridge.handle_local_request(
            {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {}}
        )
        self.assertTrue(response["result"]["capabilities"]["tools"]["listChanged"])


class RefreshNotificationTests(unittest.TestCase):
    def setUp(self):
        self.bridge = load_bridge()
        self.bridge._connection_cache = {"connected": None, "last_check": 0}

    def serve_static_tools_list(self):
        with mock.patch.object(self.bridge, "check_orcaslicer_connection", return_value=self.bridge.DOWN):
            return self.bridge.handle_local_request({"jsonrpc": "2.0", "id": 1, "method": "tools/list"})

    def test_no_notification_before_a_live_server_is_seen(self):
        self.serve_static_tools_list()
        self.assertFalse(self.bridge.tools_changed_notification_due())

    def test_no_notification_when_the_static_list_was_never_served(self):
        self.bridge._live_contact = True
        self.assertFalse(self.bridge.tools_changed_notification_due())

    def test_one_notification_after_the_static_list_and_then_a_live_server(self):
        self.serve_static_tools_list()
        self.bridge._live_contact = True
        self.assertTrue(self.bridge.tools_changed_notification_due())
        # Once only: a client that re-fetched does not need telling again every request.
        self.assertFalse(self.bridge.tools_changed_notification_due())


class StaticSchemaFreshnessTests(unittest.TestCase):
    def test_get_presets_in_the_static_list_has_its_filters(self):
        sys.path.insert(0, os.path.join(REPO_ROOT, "scripts"))
        from tools_schema import FULL_TOOLS_LIST

        entry = next(t for t in FULL_TOOLS_LIST if t["name"] == "get_presets")
        properties = entry["inputSchema"]["properties"]
        self.assertEqual(
            set(properties), {"type", "vendor", "name_contains", "summary", "limit"}
        )


if __name__ == "__main__":
    unittest.main()
