#!/usr/bin/env python3
"""Regenerate scripts/tools_schema.py from the running OrcaMCP server."""
import json, os, sys, urllib.request, pprint

HOST = os.environ.get("ORCAMCP_HOST", "localhost")
PORT = os.environ.get("ORCAMCP_PORT", "13618")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools_schema.py")

def fetch_tools():
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/list", "params": {}}).encode()
    req = urllib.request.Request(f"http://{HOST}:{PORT}/mcp", data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=5) as resp:
        return json.load(resp)["result"]["tools"]

def main():
    tools = sorted(fetch_tools(), key=lambda t: t["name"])
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Full tools list from OrcaMCP server\n")
        f.write("# This ensures schemas are always correct and match the server\n")
        f.write("# Auto-generated by scripts/regen_tools_schema.py - do not edit by hand\n\n")
        f.write("FULL_TOOLS_LIST = ")
        f.write(pprint.pformat(tools))
        f.write("\n")
    print(f"wrote {len(tools)} tools to {OUT}")

if __name__ == "__main__":
    sys.exit(main())
