# Full tools list from OrcaMCP server
# This ensures schemas are always correct and match the server
# Auto-generated by scripts/regen_tools_schema.py - do not edit by hand

FULL_TOOLS_LIST = [{'description': 'Configure a print host on the current printer preset and '
                 'save it as a user preset with this name.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'api_key': {'description': 'API key, or the '
                                                            'Flashforge LAN '
                                                            'check code. Omit '
                                                            'to keep the '
                                                            'stored one.',
                                             'type': 'string'},
                                 'host': {'description': 'IP address or '
                                                         'hostname of the '
                                                         'printer',
                                          'type': 'string'},
                                 'host_type': {'description': 'Print host type',
                                               'enum': ['flashforge',
                                                        'moonraker',
                                                        'octoprint',
                                                        'prusalink',
                                                        'duet',
                                                        'repetier',
                                                        'mks',
                                                        'elegoolink',
                                                        'crealityprint'],
                                               'type': 'string'},
                                 'name': {'description': 'Name to save the '
                                                         'printer preset '
                                                         'under, e.g. "C5P"',
                                          'type': 'string'},
                                 'printer_preset': {'description': 'Printer '
                                                                   'preset to '
                                                                   'base it on '
                                                                   '(default: '
                                                                   'the edited '
                                                                   'printer '
                                                                   'preset). '
                                                                   'Settings '
                                                                   'you do not '
                                                                   'pass are '
                                                                   'taken from '
                                                                   'that '
                                                                   'preset, so '
                                                                   'naming a '
                                                                   'different '
                                                                   'one '
                                                                   'replaces '
                                                                   'the stored '
                                                                   'credentials '
                                                                   'of an '
                                                                   'existing '
                                                                   'printer.',
                                                    'type': 'string'},
                                 'serial_number': {'description': 'Flashforge '
                                                                  'serial '
                                                                  'number '
                                                                  '(from '
                                                                  'discover_printers). '
                                                                  'Omit to '
                                                                  'keep the '
                                                                  'stored one.',
                                                   'type': 'string'}},
                  'required': ['name', 'host', 'host_type'],
                  'type': 'object'},
  'name': 'add_physical_printer'},
 {'description': 'Create a new plate.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'add_plate'},
 {'description': 'Apply Variable Layer Height based on geometry.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'object_ids': {'description': 'Object indices '
                                                               'for batch',
                                                'items': {'type': 'integer'},
                                                'type': 'array'},
                                 'quality': {'description': '0.0 (speed) to '
                                                            '1.0 (quality). '
                                                            'Default: 0.5',
                                             'type': 'number'}},
                  'required': [],
                  'type': 'object'},
  'name': 'apply_adaptive_layer_height'},
 {'description': 'Apply print settings. Batch multiple in one call. Types: '
                 'print | filament | printer | project.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'settings': {'description': 'Settings array',
                                              'items': {'properties': {'key': {'description': 'Key '
                                                                                              'name',
                                                                               'type': 'string'},
                                                                       'type': {'description': 'Setting '
                                                                                               'type',
                                                                                'enum': ['print',
                                                                                         'filament',
                                                                                         'printer',
                                                                                         'project'],
                                                                                'type': 'string'},
                                                                       'value': {'description': 'Value'}},
                                                        'required': ['type',
                                                                     'key',
                                                                     'value'],
                                                        'type': 'object'},
                                              'type': 'array'}},
                  'required': ['settings'],
                  'type': 'object'},
  'name': 'apply_config'},
 {'description': 'Automatically arrange all objects on the build plate',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'arrange_objects'},
 {'description': 'Automatically recalculate flush-volume matrices for every '
                 'physical filament and extruder from filament color/type '
                 'compatibility.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'auto_calc_flush_volumes'},
 {'description': 'Automatically orient all objects for optimal printing',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'auto_orient'},
 {'description': 'Remove Variable Layer Height, revert to fixed.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Include a '
                                                                    'preview '
                                                                    'image '
                                                                    'path to '
                                                                    'visually '
                                                                    'verify '
                                                                    'the '
                                                                    'result',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'object_ids': {'description': 'Object indices '
                                                               'for batch',
                                                'items': {'type': 'integer'},
                                                'type': 'array'}},
                  'required': [],
                  'type': 'object'},
  'name': 'clear_adaptive_layer_height'},
 {'description': 'Clone object. duplicate=true for independent copies.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'count': {'description': 'Number of copies '
                                                          '(default: 1)',
                                           'type': 'integer'},
                                 'destination_plate': {'description': 'Target '
                                                                      'plate. '
                                                                      'If '
                                                                      'omitted, '
                                                                      'uses '
                                                                      'current '
                                                                      'plate.',
                                                       'type': 'integer'},
                                 'duplicate': {'description': 'true=independent '
                                                              'copies, false '
                                                              '(default)=linked '
                                                              'instances',
                                               'type': 'boolean'},
                                 'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'clone_object'},
 {'description': 'Clone a preset with a new name.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'new_name': {'description': 'New preset name',
                                              'type': 'string'},
                                 'source_name': {'description': 'Source preset '
                                                                'name',
                                                 'type': 'string'},
                                 'type': {'description': 'Preset type',
                                          'enum': ['printer',
                                                   'filament',
                                                   'print'],
                                          'type': 'string'}},
                  'required': ['type', 'source_name', 'new_name'],
                  'type': 'object'},
  'name': 'clone_preset'},
 {'description': 'Cut object at Z height. keep: below, above, or both.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'keep': {'description': 'below (default), '
                                                         'above, or both',
                                          'enum': ['below', 'above', 'both'],
                                          'type': 'string'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'z_height': {'description': 'Cut height in mm',
                                              'type': 'number'}},
                  'required': ['object_id', 'z_height'],
                  'type': 'object'},
  'name': 'cut_object'},
 {'description': 'Delete a mixed (virtual) filament slot.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'slot': {'description': 'Mixed slot, 1-based',
                                          'type': 'integer'}},
                  'required': ['slot'],
                  'type': 'object'},
  'name': 'delete_mixed_filament'},
 {'description': 'Remove an object from the scene',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'delete_object'},
 {'description': 'Remove layer range config. If z_min/z_max omitted, removes '
                 'ALL ranges.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'z_max': {'description': 'Max Z height (mm). '
                                                          'Omit both to delete '
                                                          'all ranges.',
                                           'type': 'number'},
                                 'z_min': {'description': 'Min Z height (mm). '
                                                          'Omit both to delete '
                                                          'all ranges.',
                                           'type': 'number'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'delete_object_layer_range'},
 {'description': 'Delete a plate. Cannot delete last plate. Objects moved to '
                 'another plate.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'plate_index': {'description': 'Plate index. '
                                                                'If omitted, '
                                                                'deletes '
                                                                'current '
                                                                'plate.',
                                                 'type': 'integer'}},
                  'required': [],
                  'type': 'object'},
  'name': 'delete_plate'},
 {'description': 'Delete a user-created preset.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'name': {'description': 'Preset name',
                                          'type': 'string'},
                                 'type': {'description': 'Preset type',
                                          'enum': ['printer',
                                                   'filament',
                                                   'print'],
                                          'type': 'string'}},
                  'required': ['type', 'name'],
                  'type': 'object'},
  'name': 'delete_preset'},
 {'description': 'Discover Flashforge printers on the local network via UDP '
                 'broadcast.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'timeout_ms': {'description': 'Discovery '
                                                               'timeout in '
                                                               'milliseconds '
                                                               '(default 5000)',
                                                'type': 'integer'}},
                  'required': [],
                  'type': 'object'},
  'name': 'discover_printers'},
 {'description': 'Export project as 3MF file.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'output_path': {'description': 'Output path '
                                                                '(required; '
                                                                'file dialogs '
                                                                'cannot be '
                                                                'opened from '
                                                                'MCP).',
                                                 'type': 'string'}},
                  'required': ['output_path'],
                  'type': 'object'},
  'name': 'export_3mf'},
 {'description': 'Export G-code. Requires slicing complete.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'output_path': {'description': 'Output path '
                                                                '(required; '
                                                                'file dialogs '
                                                                'cannot be '
                                                                'opened from '
                                                                'MCP).',
                                                 'type': 'string'}},
                  'required': ['output_path'],
                  'type': 'object'},
  'name': 'export_gcode'},
 {'description': 'Automatically orient an object to lay flat on its best face '
                 'for printing',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'flatten_object'},
 {'description': 'Enumerate an achievable palette of filament mixes (pairs, '
                 "and optionally triples) from the printer's loaded physical "
                 'filaments -- a shortlist to choose from before painting.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'material_type': {'description': 'Restrict to '
                                                                  'this '
                                                                  'filament '
                                                                  'type (e.g. '
                                                                  '"PLA")',
                                                   'type': 'string'},
                                 'max_components': {'description': '2 for '
                                                                   'pairs '
                                                                   'only, 3 to '
                                                                   'also '
                                                                   'include '
                                                                   'triples. '
                                                                   'Default 2.',
                                                    'enum': [2, 3],
                                                    'type': 'integer'},
                                 'max_count': {'description': 'Max entries to '
                                                              'return, default '
                                                              '12, cap 48',
                                               'type': 'integer'}},
                  'required': [],
                  'type': 'object'},
  'name': 'get_color_palette'},
 {'description': 'Get currently edited presets with dirty (modified) options',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_edited_presets'},
 {'description': 'List all filament slots (physical and mixed/virtual), '
                 'extruder count, and filament-to-extruder map.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_filaments'},
 {'description': 'Get the per-extruder flush-volume matrices (mL to purge '
                 'switching from filament X to Y) and the flush multiplier '
                 'used to scale them.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_flush_volumes'},
 {'description': 'Get per-object setting overrides.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'get_object_config'},
 {'description': 'Get info about a single object.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'get_object_info'},
 {'description': 'Get layer-range settings for an object.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'get_object_layer_ranges'},
 {'description': 'Get all available printer, filament, and print presets',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_presets'},
 {'description': 'Convert preview image to base64. Use only if no filesystem '
                 'access.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'path': {'description': 'Path to preview '
                                                         'image file',
                                          'type': 'string'}},
                  'required': ['path'],
                  'type': 'object'},
  'name': 'get_preview_base64'},
 {'description': 'Get print time and filament estimates.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_print_estimate'},
 {'description': 'Get live status from the configured print host: state, '
                 'progress, temperatures, light, material station. Full detail '
                 'is only available for Flashforge hosts; other host types '
                 'report online/offline.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_printer_status'},
 {'description': 'Get available printers and their status.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_printers'},
 {'description': 'Get current project state: plates, objects, positions. Call '
                 'first to get object_ids.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'},
                                 'with_model_object_features': {'description': 'Include '
                                                                               'overhang, '
                                                                               'volume, '
                                                                               'etc.',
                                                                'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'get_scene_info'},
 {'description': 'Get documentation about tools, concepts, and workflows',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_server_info'},
 {'description': 'Get the current slicing status and progress',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_slicing_status'},
 {'description': 'Get toolchanger / multi-extruder settings (retraction on '
                 'toolchange, prime tower, filament map, ...) from the printer '
                 'preset, print preset, and project config.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'get_toolchanger_config'},
 {'description': 'Get valid configuration keys.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'category': {'description': 'per_object, '
                                                             'print, filament, '
                                                             'printer, '
                                                             'toolchanger, '
                                                             'project, or all',
                                              'type': 'string'},
                                 'include_descriptions': {'description': 'Include '
                                                                         'key '
                                                                         'descriptions',
                                                          'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'get_valid_config_keys'},
 {'description': 'List G-code files stored on the Flashforge printer.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'list_printer_files'},
 {'description': 'Import a 3D model file (STL, 3MF, OBJ, STEP, etc.)',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'file_path': {'description': 'Path to model '
                                                              'file',
                                               'type': 'string'},
                                 'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': ['file_path'],
                  'type': 'object'},
  'name': 'load_model'},
 {'description': 'Load a 3MF project file',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'file_path': {'description': 'Path to 3MF '
                                                              'file',
                                               'type': 'string'},
                                 'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': ['file_path'],
                  'type': 'object'},
  'name': 'load_project'},
 {'description': 'Mirror an object across the specified axis',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'axis': {'description': 'Axis: x, y, or z',
                                          'enum': ['x', 'y', 'z'],
                                          'type': 'string'},
                                 'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'}},
                  'required': ['object_id', 'axis'],
                  'type': 'object'},
  'name': 'mirror_object'},
 {'description': 'Move object by offset (relative) or to position '
                 '(relative=false).',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'},
                                 'relative': {'description': 'true '
                                                             '(default)=offset, '
                                                             'false=absolute '
                                                             'position',
                                              'type': 'boolean'},
                                 'x': {'description': 'X in mm',
                                       'type': 'number'},
                                 'y': {'description': 'Y in mm',
                                       'type': 'number'},
                                 'z': {'description': 'Z in mm',
                                       'type': 'number'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'move_object'},
 {'description': 'Create a new empty project.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'new_project'},
 {'description': 'Start printing a G-code file already stored on the '
                 'Flashforge printer, with optional material station mapping.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'auto_map': {'description': 'When true '
                                                             '(default) and '
                                                             'material_mappings '
                                                             'is not given, '
                                                             'build the '
                                                             'mapping from the '
                                                             'current '
                                                             "project's "
                                                             'filament types '
                                                             'matched against '
                                                             'the material '
                                                             "station's loaded "
                                                             'slots.',
                                              'type': 'boolean'},
                                 'file_name': {'description': 'File name as '
                                                              'returned by '
                                                              'list_printer_files',
                                               'type': 'string'},
                                 'leveling_before_print': {'description': 'Run '
                                                                          'bed '
                                                                          'leveling '
                                                                          'before '
                                                                          'printing '
                                                                          '(default '
                                                                          'false)',
                                                           'type': 'boolean'},
                                 'material_mappings': {'description': 'Explicit '
                                                                      'tool-to-slot '
                                                                      'mapping. '
                                                                      'Overrides '
                                                                      'auto_map '
                                                                      'when '
                                                                      'provided.',
                                                       'items': {'properties': {'slot_id': {'description': 'Material '
                                                                                                           'station '
                                                                                                           'slot '
                                                                                                           'id',
                                                                                            'type': 'integer'},
                                                                                'tool_id': {'description': 'Project '
                                                                                                           'filament/tool '
                                                                                                           'index, '
                                                                                                           '0-based',
                                                                                            'type': 'integer'}},
                                                                 'required': ['tool_id',
                                                                              'slot_id'],
                                                                 'type': 'object'},
                                                       'type': 'array'}},
                  'required': ['file_name'],
                  'type': 'object'},
  'name': 'print_printer_file'},
 {'description': 'Control the Flashforge printer: pause, resume or cancel the '
                 'current job, turn the enclosure light on/off, or set '
                 'bed/chamber/nozzle target temperatures.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'action': {'description': 'Control action to '
                                                           'perform',
                                            'enum': ['pause',
                                                     'resume',
                                                     'cancel',
                                                     'light_on',
                                                     'light_off',
                                                     'set_temperature'],
                                            'type': 'string'},
                                 'bed': {'description': 'set_temperature only: '
                                                        'target bed '
                                                        'temperature. Omit for '
                                                        'no change.',
                                         'type': 'number'},
                                 'chamber': {'description': 'set_temperature '
                                                            'only: target '
                                                            'chamber '
                                                            'temperature. Omit '
                                                            'for no change.',
                                             'type': 'number'},
                                 'nozzles': {'description': 'set_temperature '
                                                            'only: per-tool '
                                                            'target '
                                                            'temperatures. '
                                                            'Tools not listed '
                                                            'are left '
                                                            'unchanged.',
                                             'items': {'properties': {'temp': {'description': 'Target '
                                                                                              'temperature',
                                                                               'type': 'number'},
                                                                      'tool': {'description': 'Tool/nozzle '
                                                                                              'index, '
                                                                                              '0-3',
                                                                               'type': 'integer'}},
                                                       'required': ['tool',
                                                                    'temp'],
                                                       'type': 'object'},
                                             'type': 'array'}},
                  'required': ['action'],
                  'type': 'object'},
  'name': 'printer_control'},
 {'description': 'Redo the last undone operation',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'redo'},
 {'description': 'Rename an object for identification purposes',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'new_name': {'description': 'New name',
                                              'type': 'string'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id', 'new_name'],
                  'type': 'object'},
  'name': 'rename_object'},
 {'description': 'Render plate from custom camera angles. Use '
                 'save_to_file=true for file paths.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'plate_index': {'description': 'Plate index '
                                                                '(0-based)',
                                                 'type': 'integer'},
                                 'resolution': {'default': 512,
                                                'description': 'Resolution in '
                                                               'pixels '
                                                               '(default: 512)',
                                                'type': 'integer'},
                                 'save_to_file': {'default': False,
                                                  'description': 'Return file '
                                                                 'paths '
                                                                 'instead of '
                                                                 'base64 '
                                                                 '(default: '
                                                                 'false)',
                                                  'type': 'boolean'},
                                 'views': {'description': 'View configurations',
                                           'items': {'properties': {'camera_position': {'description': '[x, '
                                                                                                       'y, '
                                                                                                       'z]',
                                                                                        'items': {'type': 'number'},
                                                                                        'type': 'array'},
                                                                    'target': {'description': '[x, '
                                                                                              'y, '
                                                                                              'z]',
                                                                               'items': {'type': 'number'},
                                                                               'type': 'array'}},
                                                     'type': 'object'},
                                           'type': 'array'}},
                  'required': ['plate_index', 'views'],
                  'type': 'object'},
  'name': 'render_plate_view'},
 {'description': 'Remove per-object setting overrides.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'keys': {'description': 'Keys to reset. If '
                                                         'omitted, resets all '
                                                         'overrides.',
                                          'items': {'type': 'string'},
                                          'type': 'array'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'reset_object_config'},
 {'description': 'Discard unsaved preset changes.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'type': {'description': 'Preset type',
                                          'enum': ['printer',
                                                   'filament',
                                                   'print'],
                                          'type': 'string'}},
                  'required': ['type'],
                  'type': 'object'},
  'name': 'reset_preset'},
 {'description': 'Rotate object around X, Y, Z axes (degrees).',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'},
                                 'relative': {'description': 'true=add, '
                                                             'false=absolute',
                                              'type': 'boolean'},
                                 'x': {'description': 'X rotation (degrees)',
                                       'type': 'number'},
                                 'y': {'description': 'Y rotation (degrees)',
                                       'type': 'number'},
                                 'z': {'description': 'Z rotation (degrees)',
                                       'type': 'number'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'rotate_object'},
 {'description': 'Save dirty changes to preset. Optionally save as new name.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'name': {'description': 'Save as new name. If '
                                                         'omitted, saves to '
                                                         'current preset.',
                                          'type': 'string'},
                                 'type': {'description': 'Preset type',
                                          'enum': ['printer',
                                                   'filament',
                                                   'print'],
                                          'type': 'string'}},
                  'required': ['type'],
                  'type': 'object'},
  'name': 'save_preset'},
 {'description': 'Save current project.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'save_as': {'description': 'Ignored for a '
                                                            'project that '
                                                            'already has a '
                                                            'file name (it is '
                                                            'saved in place). '
                                                            'A project with no '
                                                            'file name cannot '
                                                            'be saved from '
                                                            'MCP, because that '
                                                            'needs a file '
                                                            'dialog.',
                                             'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'save_project'},
 {'description': 'Scale object by axis factors. uniform=true uses x for all.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'preview_resolution': {'description': 'Resolution '
                                                                       'in '
                                                                       'pixels '
                                                                       '(default: '
                                                                       '256)',
                                                        'type': 'integer'},
                                 'preview_views': {'description': 'Views: 4 or '
                                                                  '8 (default: '
                                                                  '4)',
                                                   'type': 'integer'},
                                 'uniform': {'description': 'If true, use x '
                                                            'for all axes '
                                                            '(default: false)',
                                             'type': 'boolean'},
                                 'x': {'description': 'X scale factor',
                                       'type': 'number'},
                                 'y': {'description': 'Y scale factor',
                                       'type': 'number'},
                                 'z': {'description': 'Z scale factor',
                                       'type': 'number'}},
                  'required': ['object_id'],
                  'type': 'object'},
  'name': 'scale_object'},
 {'description': 'Select a plate as current.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'plate_index': {'description': 'Plate index '
                                                                '(0-based)',
                                                 'type': 'integer'}},
                  'required': ['plate_index'],
                  'type': 'object'},
  'name': 'select_plate'},
 {'description': 'Select a printer, filament, or print preset by name',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'name': {'description': 'Preset name',
                                          'type': 'string'},
                                 'type': {'description': 'Preset type',
                                          'enum': ['printer',
                                                   'filament',
                                                   'print'],
                                          'type': 'string'}},
                  'required': ['type', 'name'],
                  'type': 'object'},
  'name': 'select_preset'},
 {'description': 'Select a printer: a Bambu device by dev_id, or a printer '
                 'preset with a print host by name.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'dev_id': {'description': 'Bambu device ID',
                                            'type': 'string'},
                                 'physical_printer': {'description': 'Printer '
                                                                     'preset '
                                                                     'with a '
                                                                     'print '
                                                                     'host, as '
                                                                     'listed '
                                                                     'by '
                                                                     'get_printers',
                                                      'type': 'string'}},
                  'required': [],
                  'type': 'object'},
  'name': 'select_printer'},
 {'description': 'Upload the sliced plate to the configured print host and '
                 'optionally start it. The upload runs without any dialog: on '
                 "a Flashforge printer with a material station the project's "
                 'filaments are mapped onto the loaded slots automatically '
                 '(pass material_mappings to choose the slots yourself). Pass '
                 "direct=false to open OrcaSlicer's send dialog and leave the "
                 'send to the user.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'all_plates': {'description': 'Dialog sends '
                                                               'only '
                                                               '(direct=false): '
                                                               'send all '
                                                               'plates instead '
                                                               'of the current '
                                                               'one.',
                                                'type': 'boolean'},
                                 'direct': {'description': 'When true '
                                                           '(default), upload '
                                                           'straight to the '
                                                           'printer. When '
                                                           'false, open '
                                                           "OrcaSlicer's send "
                                                           'dialog for the '
                                                           'user instead.',
                                            'type': 'boolean'},
                                 'file_name': {'description': 'Name to store '
                                                              'the upload '
                                                              'under (default: '
                                                              "the plate's own "
                                                              'output file '
                                                              'name). Direct '
                                                              'sends only.',
                                               'type': 'string'},
                                 'leveling_before_print': {'description': 'Run '
                                                                          'bed '
                                                                          'leveling '
                                                                          'before '
                                                                          'printing '
                                                                          '(default '
                                                                          'false). '
                                                                          'Direct '
                                                                          'sends '
                                                                          'only.',
                                                           'type': 'boolean'},
                                 'material_mappings': {'description': 'Explicit '
                                                                      'tool-to-slot '
                                                                      'mapping. '
                                                                      'Omit to '
                                                                      'map the '
                                                                      "project's "
                                                                      'filaments '
                                                                      'onto '
                                                                      'matching '
                                                                      'loaded '
                                                                      'slots '
                                                                      'automatically. '
                                                                      'Direct '
                                                                      'sends '
                                                                      'only.',
                                                       'items': {'properties': {'slot_id': {'description': 'Material '
                                                                                                           'station '
                                                                                                           'slot '
                                                                                                           'id',
                                                                                            'type': 'integer'},
                                                                                'tool_id': {'description': 'Project '
                                                                                                           'filament/tool '
                                                                                                           'index, '
                                                                                                           '0-based',
                                                                                            'type': 'integer'}},
                                                                 'required': ['tool_id',
                                                                              'slot_id'],
                                                                 'type': 'object'},
                                                       'type': 'array'},
                                 'start_print': {'description': 'Start '
                                                                'printing once '
                                                                'the upload '
                                                                'finishes '
                                                                '(default '
                                                                'true). Direct '
                                                                'sends only.',
                                                 'type': 'boolean'},
                                 'use_material_station': {'description': 'Print '
                                                                         'from '
                                                                         'the '
                                                                         'material '
                                                                         'station '
                                                                         '(default: '
                                                                         'true '
                                                                         'when '
                                                                         'the '
                                                                         'Flashforge '
                                                                         'printer '
                                                                         'reports '
                                                                         'one). '
                                                                         'Direct '
                                                                         'sends '
                                                                         'only.',
                                                          'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'send_to_printer'},
 {'description': "Overwrite one extruder's full flush-volume matrix (NxN, N = "
                 "physical filament count) and, optionally, that extruder's "
                 'flush multiplier.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'extruder': {'description': '0-based '
                                                             'extruder, '
                                                             'default 0',
                                              'type': 'integer'},
                                 'flush_multiplier': {'description': 'Optional '
                                                                     'scale '
                                                                     'factor '
                                                                     'for this '
                                                                     'extruder',
                                                      'type': 'number'},
                                 'matrix': {'description': 'NxN matrix, row = '
                                                           'from-filament, '
                                                           'column = '
                                                           'to-filament, mL',
                                            'items': {'items': {'type': 'number'},
                                                      'type': 'array'},
                                            'type': 'array'}},
                  'required': ['matrix'],
                  'type': 'object'},
  'name': 'set_flush_volumes'},
 {'description': 'Set G-code preview visualization mode. Requires sliced '
                 'G-code. Available types: feature_type, speed, actual_speed, '
                 'fan_speed, temperature, flow, actual_flow, layer_height, '
                 'line_width, layer_time, layer_time_log, pressure_advance, '
                 'acceleration, jerk, tool, filament',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'view_type': {'description': 'Visualization '
                                                              'mode for G-code '
                                                              'preview',
                                               'enum': ['feature_type',
                                                        'speed',
                                                        'actual_speed',
                                                        'fan_speed',
                                                        'temperature',
                                                        'flow',
                                                        'actual_flow',
                                                        'layer_height',
                                                        'line_width',
                                                        'layer_time',
                                                        'layer_time_log',
                                                        'pressure_advance',
                                                        'acceleration',
                                                        'jerk',
                                                        'tool',
                                                        'filament'],
                                               'type': 'string'}},
                  'required': ['view_type'],
                  'type': 'object'},
  'name': 'set_gcode_view_type'},
 {'description': 'Create or edit a mixed (virtual) filament slot that '
                 'alternates two or three physical filaments by layer ratio. '
                 'Requires a multi-filament printer profile.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'components': {'description': '2-3 physical '
                                                               'filament '
                                                               'slots, 1-based',
                                                'items': {'type': 'integer'},
                                                'type': 'array'},
                                 'gradient': {'description': 'Z gradient '
                                                             'between the two '
                                                             'components',
                                              'type': 'boolean'},
                                 'gradient_direction': {'enum': ['a_to_b',
                                                                 'b_to_a'],
                                                        'type': 'string'},
                                 'per_part_gradient': {'type': 'boolean'},
                                 'ratios': {'description': 'Percent per '
                                                           'component, must '
                                                           'sum to 100',
                                            'items': {'type': 'integer'},
                                            'type': 'array'},
                                 'slot': {'description': 'Existing mixed slot '
                                                         'to edit (1-based). '
                                                         'Omit to create.',
                                          'type': 'integer'}},
                  'required': ['components', 'ratios'],
                  'type': 'object'},
  'name': 'set_mixed_filament'},
 {'description': 'Set per-object setting overrides.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'configs': {'description': 'Batch configs '
                                                            'array',
                                             'items': {'additionalProperties': False,
                                                       'properties': {'object_id': {'type': 'integer'},
                                                                      'settings': {'items': {'additionalProperties': False,
                                                                                             'properties': {'key': {'type': 'string'},
                                                                                                            'value': {'type': 'string'}},
                                                                                             'required': ['key',
                                                                                                          'value'],
                                                                                             'type': 'object'},
                                                                                   'type': 'array'}},
                                                       'required': ['object_id',
                                                                    'settings'],
                                                       'type': 'object'},
                                             'type': 'array'},
                                 'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'settings': {'description': 'Settings array',
                                              'items': {'additionalProperties': False,
                                                        'properties': {'key': {'type': 'string'},
                                                                       'value': {'description': 'Value',
                                                                                 'type': 'string'}},
                                                        'required': ['key',
                                                                     'value'],
                                                        'type': 'object'},
                                              'type': 'array'}},
                  'required': [],
                  'type': 'object'},
  'name': 'set_object_config'},
 {'description': 'Assign a filament slot (physical or mixed) to an object, or '
                 'to one part/modifier of it.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'filament': {'description': 'Filament slot, '
                                                             '1-based',
                                              'type': 'integer'},
                                 'object_id': {'type': 'integer'},
                                 'volume_id': {'description': 'Part index '
                                                              'within the '
                                                              'object; omit '
                                                              'for the whole '
                                                              'object',
                                               'type': 'integer'}},
                  'required': ['object_id', 'filament'],
                  'type': 'object'},
  'name': 'set_object_filament'},
 {'description': 'Set settings for a Z height range.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'settings': {'description': 'Settings array',
                                              'items': {'additionalProperties': False,
                                                        'properties': {'key': {'description': 'Key '
                                                                                              'name',
                                                                               'type': 'string'},
                                                                       'value': {'description': 'Value',
                                                                                 'type': 'string'}},
                                                        'required': ['key',
                                                                     'value'],
                                                        'type': 'object'},
                                              'type': 'array'},
                                 'z_max': {'description': 'Max Z height (mm)',
                                           'type': 'number'},
                                 'z_min': {'description': 'Min Z height (mm)',
                                           'type': 'number'}},
                  'required': ['object_id', 'z_min', 'z_max', 'settings'],
                  'type': 'object'},
  'name': 'set_object_layer_range'},
 {'description': 'Mark an object printable (included when slicing) or '
                 'unprintable (skipped). Useful for excluding specific objects '
                 'from a print without removing them from the scene.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'object_id': {'description': 'Object index '
                                                              '(0-based)',
                                               'type': 'integer'},
                                 'printable': {'description': 'true to include '
                                                              'in slicing, '
                                                              'false to skip',
                                               'type': 'boolean'}},
                  'required': ['object_id', 'printable'],
                  'type': 'object'},
  'name': 'set_object_printable'},
 {'description': 'Start slicing all plates. Poll get_slicing_status until '
                 'done.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {},
                  'required': [],
                  'type': 'object'},
  'name': 'slice_all'},
 {'description': 'Suggest the closest achievable 2-3 component filament mix '
                 "for a target color, from the printer's loaded physical "
                 'filaments. Optionally create the mixed slot.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'create': {'description': 'When true, create '
                                                           'the mixed slot via '
                                                           'apply_mixed_filament. '
                                                           'Default false.',
                                            'type': 'boolean'},
                                 'material_type': {'description': 'Restrict '
                                                                  'components '
                                                                  'to this '
                                                                  'filament '
                                                                  'type (e.g. '
                                                                  '"PLA"). '
                                                                  'Default: '
                                                                  'type of '
                                                                  'filament '
                                                                  'slot 1.',
                                                   'type': 'string'},
                                 'target_color': {'description': 'Target '
                                                                 'color, '
                                                                 '"#RRGGBB"',
                                                  'type': 'string'}},
                  'required': ['target_color'],
                  'type': 'object'},
  'name': 'suggest_color_mix'},
 {'description': 'Batch transform multiple objects.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'transforms': {'description': 'Transform '
                                                               'operations',
                                                'items': {'additionalProperties': False,
                                                          'properties': {'object_id': {'description': 'Object '
                                                                                                      'index '
                                                                                                      '(0-based)',
                                                                                       'type': 'integer'},
                                                                         'position': {'additionalProperties': False,
                                                                                      'description': 'Absolute '
                                                                                                     'position '
                                                                                                     '{x, '
                                                                                                     'y, '
                                                                                                     'z} '
                                                                                                     '- '
                                                                                                     'unspecified '
                                                                                                     'axes '
                                                                                                     'preserved',
                                                                                      'properties': {'x': {'type': 'number'},
                                                                                                     'y': {'type': 'number'},
                                                                                                     'z': {'type': 'number'}},
                                                                                      'type': 'object'},
                                                                         'rotation': {'additionalProperties': False,
                                                                                      'description': 'Rotation '
                                                                                                     'in '
                                                                                                     'degrees '
                                                                                                     '{x, '
                                                                                                     'y, '
                                                                                                     'z} '
                                                                                                     '- '
                                                                                                     'applied '
                                                                                                     'incrementally',
                                                                                      'properties': {'x': {'type': 'number'},
                                                                                                     'y': {'type': 'number'},
                                                                                                     'z': {'type': 'number'}},
                                                                                      'type': 'object'},
                                                                         'scale': {'additionalProperties': False,
                                                                                   'description': 'Scale '
                                                                                                  'factors '
                                                                                                  '{x, '
                                                                                                  'y, '
                                                                                                  'z} '
                                                                                                  'or '
                                                                                                  '{uniform: '
                                                                                                  'value}',
                                                                                   'properties': {'uniform': {'type': 'number'},
                                                                                                  'x': {'type': 'number'},
                                                                                                  'y': {'type': 'number'},
                                                                                                  'z': {'type': 'number'}},
                                                                                   'type': 'object'}},
                                                          'required': ['object_id'],
                                                          'type': 'object'},
                                                'type': 'array'}},
                  'required': ['transforms'],
                  'type': 'object'},
  'name': 'transform_objects'},
 {'description': 'Undo the last operation.',
  'inputSchema': {'additionalProperties': False,
                  'properties': {'include_preview': {'description': 'Return '
                                                                    'turntable '
                                                                    'preview '
                                                                    'path',
                                                     'type': 'boolean'}},
                  'required': [],
                  'type': 'object'},
  'name': 'undo'}]
